module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        backgroundsprimary: "var(--backgroundsprimary)",
        black: "var(--black)",
        dark: "var(--dark)",
        "error-300": "var(--error-300)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "green-500": "var(--green-500)",
        "green-600": "var(--green-600)",
        "grey-600": "var(--grey-600)",
        "grey-900": "var(--grey-900)",
        "neutral-500": "var(--neutral-500)",
        "office-brown900": "var(--office-brown900)",
        "primary-200": "var(--primary-200)",
        "primary-300": "var(--primary-300)",
        "primary-400": "var(--primary-400)",
        "primary-50": "var(--primary-50)",
        "primary-500": "var(--primary-500)",
        "primary-600": "var(--primary-600)",
        "primary-700": "var(--primary-700)",
        "primary-900": "var(--primary-900)",
        "red-500": "var(--red-500)",
        shadewhite: "var(--shadewhite)",
        style: "var(--style)",
        "success-100": "var(--success-100)",
        "success-300": "var(--success-300)",
        "sunnyside-yellow": "var(--sunnyside-yellow)",
        "warning-100": "var(--warning-100)",
        "warning-300": "var(--warning-300)",
        white: "var(--white)",
        "yellow-300": "var(--yellow-300)",
        "yellow-400": "var(--yellow-400)",
        "yellow-500": "var(--yellow-500)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        inter: ["var(--font-inter)", "Helvetica", "sans-serif"],
        "display-large-semibold": "var(--display-large-semibold-font-family)",
        "heading-h5-semibold": "var(--heading-h5-semibold-font-family)",
        "heading-h6-medium": "var(--heading-h6-medium-font-family)",
        "inter-body-medium": "var(--inter-body-medium-font-family)",
        "inter-body-semibold": "var(--inter-body-semibold-font-family)",
        "inter-caption-regular": "var(--inter-caption-regular-font-family)",
        "inter-caption-semibold": "var(--inter-caption-semibold-font-family)",
        "inter-h1-bold": "var(--inter-h1-bold-font-family)",
        "inter-h2-bold": "var(--inter-h2-bold-font-family)",
        "inter-h2-medium": "var(--inter-h2-medium-font-family)",
        "inter-h2-semibold": "var(--inter-h2-semibold-font-family)",
        "inter-h3-semibold": "var(--inter-h3-semibold-font-family)",
        "inter-h5-bold": "var(--inter-h5-bold-font-family)",
        "inter-h5-medium": "var(--inter-h5-medium-font-family)",
        "inter-h5-regular": "var(--inter-h5-regular-font-family)",
        "inter-h5-semibold": "var(--inter-h5-semibold-font-family)",
        "inter-title-1-medium": "var(--inter-title-1-medium-font-family)",
        "inter-title-1-regular": "var(--inter-title-1-regular-font-family)",
        "inter-title-1-semibold": "var(--inter-title-1-semibold-font-family)",
        "inter-title-2-medium": "var(--inter-title-2-medium-font-family)",
        "inter-title-2-regular": "var(--inter-title-2-regular-font-family)",
        "paragraph-medium-semibold":
          "var(--paragraph-medium-semibold-font-family)",
        sans: [
          "var(--font-inter)",
          "Helvetica",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "shadow-2": "var(--shadow-2)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
